language: generic
os: osx
osx_image: xcode7.2

before_script:
  - git clone https://github.com/tokuhirom/plenv.git ~/.plenv
  - echo 'export PATH="$HOME/.plenv/bin:$PATH"' >> ~/.bash_profile
  - echo 'eval "$(plenv init -)"' >> ~/.bash_profile
  - exec $SHELL -l
  - git clone https://github.com/tokuhirom/Perl-Build.git ~/.plenv/plugins/perl-build/
  - plenv install 5.18.0
  - plenv rehash

  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov

script:
  - perl Build.PL
  - ./Build
  - ./Build test
  - ./Build install
  - cover -test

after_success:
  - cover -report codecov

notifications:
  email: false
