language: generic
os: osx
osx_image: xcode7.2

install:
  - brew update
  - brew install plenv
  - brew install perl-build
  - eval "$(plenv init -)"
  - plenv install 5.14.0 &> /dev/null
  - plenv global 5.14.0
  - perl --version
  - plenv rehash
  - perl --version
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov

script:
  - perl Build.PL
  - ./Build
  - ./Build test
  - ./Build install
  - cover -test

after_success:
  - cover -report codecov

notifications:
  email: false
