language: perl

matrix:
  include:
    # Linux
    - perl: "5.22"
      os: linux
    # OSX
    - language: generic
      os: osx
      osx_image: xcode7.2
      env: TOXENV=5.14.0
    - language: generic
      os: osx
      osx_image: xcode7.2
      env: TOXENV=5.16.1

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh

after_success:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then cover -report codecov; fi

notifications:
  email: false
