language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

# OSX not supported:
#   https://docs.travis-ci.com/user/multi-os/
#   https://docs.travis-ci.com/user/languages/perl
os:
  - linux
  - osx

before_script:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov; fi

script:
  - perl Build.PL
  - ./Build
  - ./Build test
  - ./Build install
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then cover -test; fi

after_success:
  - cover -report codecov

notifications:
  email: false
