language: generic
os: osx
osx_image: xcode7.2

install:
  - brew update
  - brew install plenv
  - brew install perl-build
  #- git clone https://github.com/tokuhirom/plenv.git ~/.plenv
  #- echo 'export PATH="$HOME/.plenv/bin:$PATH"'
  #- echo 'eval "$(plenv init -)"'
  #- exec $SHELL -l
  #- git clone https://github.com/tokuhirom/Perl-Build.git ~/.plenv/plugins/perl-build/
  #- echo 'TEST'
  #- plenv install 5.18.0
  #- plenv rehash

  #- cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov

script:
  - perl Build.PL
  - ./Build
  - ./Build test
  - ./Build install
  - cover -test

after_success:
  - cover -report codecov

notifications:
  email: false
