install:
  - choco install strawberryperl -version 5.20.1.1
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%

test_script:
  - perl Build.PL
  - Build
  - Build test
  - Build install

cache:
  - local

 build: off
